services:
  db-postgres-api-patient:
    image: postgres:latest
    container_name: db-postgres-api-patient
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-api-patient:
    build: .
    image: welderessutti/api-patient:latest
    container_name: app-api-patient
    ports:
      - "8080:8080"
    depends_on:
      db-postgres-api-patient:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db-postgres-api-patient:5432/patient"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
