services:
  postgres:
    image: postgres
    container_name: db-postgres-api-patient
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: welderessutti/api-patient:latest
    container_name: app-api-patient
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PROFILE: "${PROFILE:-prd}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/patient"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
